package idcard;

import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import java.io.FileNotFoundException;
import java.io.UnsupportedEncodingException;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lib.RDNIDlibD;
/**
 *
 * @author WINDOWS
 */
public class GUI extends javax.swing.JFrame {

    private IDCard idcard;
    private RDNIDlibD func;
    private ConnectDB connectDB;
    private Object db;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPanel3 = new javax.swing.JPanel();
        ThaiButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        ForeignerButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        MaleButton = new javax.swing.JRadioButton();
        OtherButton = new javax.swing.JRadioButton();
        FemaleButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        IDNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        HNNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TitleName = new javax.swing.JTextField();
        FirstNameEng = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LastNameEng = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        telephone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        FirstNameThai = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        LastNameThai = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        BirthDate = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        BirthMonth = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Disease = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Description = new javax.swing.JTextField();
        cardReader = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        BirthYear = new javax.swing.JTextField();
        DB = new javax.swing.JButton();
        IDPassport = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(106, 188, 190));

        ThaiButton.setBackground(new java.awt.Color(106, 188, 190));
        buttonGroup2.add(ThaiButton);
        ThaiButton.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        ThaiButton.setText("Thai");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setText("Nationality*:");

        ForeignerButton.setBackground(new java.awt.Color(106, 188, 190));
        buttonGroup2.add(ForeignerButton);
        ForeignerButton.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        ForeignerButton.setText("Foreigner");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setText("Gender*:");

        MaleButton.setBackground(new java.awt.Color(106, 188, 190));
        buttonGroup1.add(MaleButton);
        MaleButton.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        MaleButton.setText("Male");

        OtherButton.setBackground(new java.awt.Color(106, 188, 190));
        buttonGroup1.add(OtherButton);
        OtherButton.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        OtherButton.setText("Other");
        OtherButton.setActionCommand("");

        FemaleButton.setBackground(new java.awt.Color(106, 188, 190));
        buttonGroup1.add(FemaleButton);
        FemaleButton.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        FemaleButton.setText("Female");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setText("ID Number:");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        IDNumber.setBackground(new java.awt.Color(106, 188, 190));
        IDNumber.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        IDNumber.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setText("Passport Number:");

        HNNum.setBackground(new java.awt.Color(106, 188, 190));
        HNNum.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        HNNum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setText("HN Number:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setText("Birthday/Age*:");

        TitleName.setBackground(new java.awt.Color(106, 188, 190));
        TitleName.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        TitleName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        FirstNameEng.setBackground(new java.awt.Color(106, 188, 190));
        FirstNameEng.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        FirstNameEng.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel8.setText("First Name*:");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel9.setText("Last Name*:");

        LastNameEng.setBackground(new java.awt.Color(106, 188, 190));
        LastNameEng.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        LastNameEng.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel10.setText("Telephone:");

        telephone.setBackground(new java.awt.Color(106, 188, 190));
        telephone.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        telephone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel11.setFont(new java.awt.Font("TH Sarabun New", 1, 40)); // NOI18N
        jLabel11.setText("ชื่อ:");

        FirstNameThai.setBackground(new java.awt.Color(106, 188, 190));
        FirstNameThai.setFont(new java.awt.Font("TH Sarabun New", 0, 40)); // NOI18N
        FirstNameThai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel12.setFont(new java.awt.Font("TH Sarabun New", 1, 40)); // NOI18N
        jLabel12.setText("นามสกุล:");

        LastNameThai.setBackground(new java.awt.Color(106, 188, 190));
        LastNameThai.setFont(new java.awt.Font("TH Sarabun New", 0, 40)); // NOI18N
        LastNameThai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel13.setText("Title Name:");

        BirthDate.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        BirthDate.setMaximumRowCount(31);
        BirthDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel14.setText("Birthday:");

        BirthMonth.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        BirthMonth.setMaximumRowCount(12);
        BirthMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel16.setText("Patient Address:");

        Address.setBackground(new java.awt.Color(106, 188, 190));
        Address.setFont(new java.awt.Font("TH Sarabun New", 1, 26)); // NOI18N
        Address.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel17.setText("Patient Disease:");

        Disease.setBackground(new java.awt.Color(106, 188, 190));
        Disease.setFont(new java.awt.Font("TH Sarabun New", 1, 40)); // NOI18N
        Disease.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel18.setText("Patient Description:");

        Description.setBackground(new java.awt.Color(106, 188, 190));
        Description.setFont(new java.awt.Font("TH Sarabun New", 1, 40)); // NOI18N
        Description.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        cardReader.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        cardReader.setText("ID card Reader");
        cardReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardReaderActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        clear.setText("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        BirthYear.setBackground(new java.awt.Color(106, 188, 190));
        BirthYear.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        BirthYear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        DB.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        DB.setText("move to DB");
        DB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DBActionPerformed(evt);
            }
        });

        IDPassport.setBackground(new java.awt.Color(106, 188, 190));
        IDPassport.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        IDPassport.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(76, 76, 76)
                                        .addComponent(FirstNameEng, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(76, 76, 76)
                                        .addComponent(FirstNameThai, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TitleName, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(111, 111, 111)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(76, 76, 76)
                                        .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(76, 76, 76)
                                        .addComponent(LastNameThai, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(76, 76, 76)
                                        .addComponent(LastNameEng, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(88, 88, 88)
                                .addComponent(jLabel14)
                                .addGap(40, 40, 40)
                                .addComponent(BirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(BirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(BirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(104, 104, 104)
                        .addComponent(jSeparator1)
                        .addGap(668, 668, 668))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(ThaiButton)
                                .addGap(29, 29, 29)
                                .addComponent(ForeignerButton)
                                .addGap(508, 508, 508)
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addComponent(MaleButton)
                                .addGap(16, 16, 16)
                                .addComponent(FemaleButton)
                                .addGap(18, 18, 18)
                                .addComponent(OtherButton))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(IDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IDPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HNNum, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(398, 398, 398)
                                .addComponent(jLabel17))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Address, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                                    .addComponent(Description))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Disease, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cardReader, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(DB, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThaiButton)
                    .addComponent(jLabel2)
                    .addComponent(ForeignerButton)
                    .addComponent(MaleButton)
                    .addComponent(jLabel3)
                    .addComponent(OtherButton)
                    .addComponent(FemaleButton))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(IDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(HNNum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TitleName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addComponent(jLabel10))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LastNameEng, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(FirstNameEng, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastNameThai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FirstNameThai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addComponent(jLabel12))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel14)
                            .addComponent(BirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Disease, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cardReader, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(56, 160, 166));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Patient Info");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DBActionPerformed
      
        InsertDataToDB obj = null;
        try {
            obj = new InsertDataToDB();
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        String nation = null;
        char sex;
        
        if(ThaiButton.isSelected()){
            nation = "Thai";
        } else {
            nation = "Foreigner";
        }
        obj.setNation(nation); 
        
        if(MaleButton.isSelected()){
            sex = 'M';
        } else if(FemaleButton.isSelected()){
            sex = 'F';
        } else {
            sex = 'O';
        }
        obj.setGender(sex);
        
        obj.setIDPerson(IDNumber.getText());
        obj.setIDPassport(IDPassport.getText());
        obj.setHNNum(HNNum.getText());
        obj.setFirstNameEN(FirstNameEng.getText());
        obj.setLastNameEN(LastNameEng.getText());
        obj.setFirstNameTH(FirstNameThai.getText());
        obj.setLastNameTH(LastNameThai.getText());
        obj.setTitleNameEng(TitleName.getText());
        obj.setAddress(Address.getText());
        obj.setTelephone(telephone.getText());
        obj.setDisease(Disease.getText());
        obj.setDescription(Description.getText());
        obj.setBirthDate(BirthDate.getSelectedItem().toString());
        obj.setBirthMonth(BirthMonth.getSelectedItem().toString());
        obj.setBirthYear(BirthYear.getText());
        
        
        
        if (!IDNumber.getText().equals("") && !FirstNameEng.getText().equals("") && !LastNameEng.getText().equals("") 
                && !BirthYear.getText().equals("") && buttonGroup1.getSelection()!=null && buttonGroup2.getSelection()!=null){
 
            obj.start();
            JOptionPane.showMessageDialog(GUI.this, "complete!");

       
        } else {
            
            JOptionPane.showMessageDialog(GUI.this, "please fill in all required field!");
        }
        
        
        
        
        
    }//GEN-LAST:event_DBActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        
        IDNumber.setText("");
        IDPassport.setText("");
        TitleName.setText("");
        FirstNameEng.setText("");
        LastNameEng.setText("");
        FirstNameThai.setText("");
        LastNameThai.setText("");
        BirthYear.setText("");
        Address.setText("");
        Description.setText("");
        Disease.setText("");
        BirthDate.setSelectedItem("01");
        BirthMonth.setSelectedItem("01");
        
    }//GEN-LAST:event_clearActionPerformed

    private void cardReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardReaderActionPerformed
        
        idcard = new IDCard();
        
        //----- insert ID card -> nationality = Thai
        ThaiButton.setSelected(true);
        
        //----- open ID card reader: ready to work
        idcard.openReader();
        
        //----- get information dict from IDCard.java
        idcard.getText();
        idcard.getInfoDict();
        
        IDNumber.setText(idcard.getInfoDict().get("IDNumber"));
        TitleName.setText(idcard.getInfoDict().get("TitleNameEN"));
        FirstNameEng.setText(idcard.getInfoDict().get("FirstNameEN"));
        LastNameEng.setText(idcard.getInfoDict().get("LastNameEN"));
        FirstNameThai.setText(idcard.getInfoDict().get("FirstNameTH"));
        LastNameThai.setText(idcard.getInfoDict().get("LastNameTH"));
        
        //----- address
        Address.setText(idcard.getInfoDict().get("HOME_NO") + " " + idcard.getInfoDict().get("MOO") + " " + idcard.getInfoDict().get("TROK") + " " + idcard.getInfoDict().get("SOI")
            + " " + idcard.getInfoDict().get("ROAD") + " " + idcard.getInfoDict().get("TUMBON") + " " + idcard.getInfoDict().get("AMPHOE") + " " + idcard.getInfoDict().get("PROVINCE"));

        //----- gender
        if("M".equals(idcard.getInfoDict().get("Gender"))){
            MaleButton.setSelected(true);
        } else if("F".equals(idcard.getInfoDict().get("Gender"))){
            FemaleButton.setSelected(true);
        }

        BirthDate.setSelectedItem(idcard.getInfoDict().get("BirthDate"));
        BirthMonth.setSelectedItem(idcard.getInfoDict().get("BirthMonth"));
        BirthYear.setText(idcard.getInfoDict().get("BirthYear"));
        
    }//GEN-LAST:event_cardReaderActionPerformed

       public static void main(String args[]) {
        NativeLibrary.addSearchPath("RDNIDlibD", "D:\\intern CTI\\IDCard\\");
//        RDNIDlibD func = (RDNIDlibD) Native.loadLibrary("RDNIDlibD", RDNIDlibD.class);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JComboBox<String> BirthDate;
    private javax.swing.JComboBox<String> BirthMonth;
    private javax.swing.JTextField BirthYear;
    private javax.swing.JButton DB;
    private javax.swing.JTextField Description;
    private javax.swing.JTextField Disease;
    private javax.swing.JRadioButton FemaleButton;
    private javax.swing.JTextField FirstNameEng;
    private javax.swing.JTextField FirstNameThai;
    private javax.swing.JRadioButton ForeignerButton;
    private javax.swing.JTextField HNNum;
    private javax.swing.JTextField IDNumber;
    private javax.swing.JTextField IDPassport;
    private javax.swing.JTextField LastNameEng;
    private javax.swing.JTextField LastNameThai;
    private javax.swing.JRadioButton MaleButton;
    private javax.swing.JRadioButton OtherButton;
    private javax.swing.JRadioButton ThaiButton;
    private javax.swing.JTextField TitleName;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton cardReader;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField telephone;
    // End of variables declaration//GEN-END:variables
}
